name: multiplexdesigner-run
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - primer3-py>=2.2.0
  - bedtools>=2.30.0
  - blast>=2.12.0
  - rich
  - pandas>=1.5.0
  - numpy>=1.22.0
  - pysam>=0.19.0
  - scipy>=1.7.0
  - seaborn>=0.11.2
  - matplotlib
  - numba>=0.55.2
  - pip
